version: "3.9"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
  driver-location-api:
    build: ./driver-location-api
    networks:
      - app_network
  matching-api:
    build: ./matching-api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge