openapi: 3.0.0
info:
  title: Matching API
  version: 1.0.0
  description: API that matches users and drivers based on their location.
paths:
  /api/v1/match/driver:
    post:
      summary: Get nearest driver location
      description: Retrieves the location of the nearest driver based on the given user location.
      parameters:
        - name: Authorization
          in: header
          description: Authorization token
          required: true
          schema:
            type: string
        - name: radius
          in: query
          description: Radius in meters for searching drivers
          required: true
          schema:
            type: number
            format: float
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLocation'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/DriverLocationResponse'
        '400':
          description: Bad request, invalid input
        '401':
          description: Unauthorized
        '404':
          description: Driver location not found
        '500':
          description: Internal server error
  /api/v1/auth:
    post:
      summary: Authenticate user
      description: Verifies the provided authorization token
      parameters:
        - name: Authorization
          in: header
          description: Authorization token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Authentication successful
        '401':
          description: Unauthorized
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    UserLocation:
      type: object
      properties:
        type:
          type: string
          enum: ["Point"]
        coordinates:
          type: array
          items:
            type: number
          example:
            - -122.4194
            - 37.7749
    DriverLocationResponse:
      type: object
      properties:
        driverLocation:
          type: object
          properties:
            type:
              type: string
              enum: ["Point"]
            coordinates:
              type: array
              items:
                type: number
              example:
                - -122.4194
                - 37.7749
        distance:
          type: object
          properties:
            distance:
              type: number
              format: float
              example: 10
            unit:
              type: string
              example: km